.TH NETWORKSTAT 1 "March 2025" "Version 1.0.0" "XILYOR Tools"
.SH NAME
networkstat \- Monitor network interface statistics with flair
.SH SYNOPSIS
.B networkstat
[\fIoptions\fR] [\fIinterfaces\fR]

.SH DESCRIPTION
\fBnetworkstat\fR is a Python-powered network interface monitoring tool with colorful output and emoji-based indicators. It shows download/upload rates for selected interfaces.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show help menu with XILYOR ASCII branding and command list.

.TP
.B \-v, \-\-version
Show version info.

.TP
.B \-l, \-\-list
List available network interfaces on the system.

.TP
.B \-w, \-\-watch
Continuously monitor and update interface stats every second.

.TP
.B \-s, \-\-sleep \fISECONDS\fR
Override the default watch interval (in seconds).

.TP
.B \-ds, \-\-default-sleep \fISECONDS\fR
Set a new default sleep duration and save it to your config.

.TP
.B \fIinterfaces\fR
Pipe-separated list of interface names (e.g. enp0s3|wlp2s0).

.SH EXAMPLES
.B networkstat --list
.br
Show all available network interfaces.

.B networkstat enp0s3
.br
Show stats for a single interface.

.B networkstat enp0s3|wlp2s0 --watch --sleep 2
.br
Watch multiple interfaces, refreshing every 2 seconds.

.B networkstat --default-sleep 3
.br
Set and save the default sleep interval.

.SH FILES
.TP
~/.config/networkstat/config.json
User config storing default sleep duration.

.SH AUTHOR
Created by Mohamed Elleuch for XILYOR.

.SH BUGS
Please report issues to: \fImohamed.elleuch@xilyor.com\fR

.SH SEE ALSO
.BR ifconfig (8),
.BR ip (8),
.BR psutil (3)

